CREATE TABLE IF NOT EXISTS produtos (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nome VARCHAR(255) NOT NULL,
       descricao VARCHAR(255) NOT NULL,
       preco DECIMAL(19, 2) NOT NULL,
       quantidade_estoque INTEGER NOT NULL
    );
